# Use an official Nginx runtime as a parent image
FROM nginx:latest

# Copy the local index.html file to the default Nginx html directory
COPY index.html /usr/share/nginx/html

# Expose port 80
EXPOSE 80
